# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-17 09:47


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('view_name', models.CharField(max_length=25)),
                ('view_desc', models.TextField()),
                ('view_rate', models.CharField(max_length=5)),
                ('advise_time', models.CharField(max_length=20)),
            ],
        ),
    ]
