# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-18 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtUser',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('sex', models.CharField(blank=True, max_length=2, null=True)),
                ('autograph', models.CharField(blank=True, max_length=50, null=True)),
                ('greet', models.CharField(blank=True, max_length=50, null=True)),
                ('labels', models.CharField(blank=True, max_length=50, null=True)),
                ('register_date', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
