# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-20 08:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_auto_20180419_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
