# Generated by Django 5.2 on 2025-04-23 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_travelinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('travel_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app01.travelinfo')),
            ],
        ),
    ]
