# Generated by Django 5.2 on 2025-04-24 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='feedback',
            name='approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='review_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='travel_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.travelinfo'),
        ),
    ]
